### ISSUE TITLE
This app cant run on your pc

### ISSUE THREAD

**Issue by brobloxb228** [zCubed3/asset_migrator#2]
![image](https://github.com/zCubed3/asset_migrator/assets/77943936/1f2864c9-2d03-4660-8c56-25b3d930b7e5)
i have had this issue for a while now

**Comment by zCubed3** [comment]
What version of windows are you running?

**Comment by brobloxb228** [comment]
> What version of windows are you running?

im using windows 11 on a x64 bit computer

**Comment by zCubed3** [comment]
That's weird because I built the release on Windows 11 x64 too. Are your windows defender / smartscreen settings increased? Because otherwise there should be zero reason this isn't working

**Comment by brobloxb228** [comment]
> That's weird because I built the release on Windows 11 x64 too. Are your windows defender / smartscreen settings increased? Because otherwise there should be zero reason this isn't working

ok i will disable them to try if it works without them

**Comment by brobloxb228** [comment]
> That's weird because I built the release on Windows 11 x64 too. Are your windows defender / smartscreen settings increased? Because otherwise there should be zero reason this isn't working

my smartscreen is off
and it still doesnt work!

**Comment by zCubed3** [comment]
Are you in the bonelab discord? If so, that would be a better place to communicate about this issue, please create a thread in mod-help (if you're in the server)

**Comment by zCubed3** [comment]
Closed due to inactivity
