### ISSUE TITLE
Conversion Stage immediately exits & Non-BONELAB game question

### ISSUE THREAD

**Issue by TheUltimateNuke** [zCubed3/asset_migrator#3]
I'm attempting to run asset_migrator.exe in Windows (10) Terminal in a D: drive, passing in my ripped project's Assets folder as the first argument and the destination Assets folder as the second. My final command looks like this:
``` .\asset_migrator.exe "D:\SteamLibrary\steamapps\common\<game>\<game>_Data\Ripped\<game>\ExportedProject\Assets" "D:\Dev Stuff\Projects\VS Community\Unity\My project\Assets"```
 
_The collection stage only lasts a couple seconds and the program exits silently immediately after the conversion stage._     

![image_2023-10-30_162500825](https://github.com/zCubed3/asset_migrator/assets/84410206/49a6705b-14cc-40db-902e-55a0da29c194)

 
 Also possibly related, is there any BONELAB/IL2CPP-specific code in this? I'm asking because I'm ripping a game with a Mono backend.

**Comment by zCubed3** [comment]
There's no specific code for BONELAB. I've actually used this tool in personal projects to port over old maps. 

Although the problem you're experiencing is poor documentation and terrible instructions on my part, sorry!

After you specify the input asset directory and output asset directory you must specify the assets you want to convert over. Such as this `./asset_migrator.exe "C:/SrcProject/Assets" "C:/DstProject/Assets" "MyScene.unity"`. Then after running this command you should see `MyScene.unity` and dependent assets inside of the `ConversionOutput` folder. You can then copy these into the destination project and everything should work as-is

**Comment by TheUltimateNuke** [comment]
> There's no specific code for BONELAB. I've actually used this tool in personal projects to port over old maps.
> 
> Although the problem you're experiencing is poor documentation and terrible instructions on my part, sorry!
> 
> After you specify the input asset directory and output asset directory you must specify the assets you want to convert over. Such as this `./asset_migrator.exe "C:/SrcProject/Assets" "C:/DstProject/Assets" "MyScene.unity"`. Then after running this command you should see `MyScene.unity` and dependent assets inside of the `ConversionOutput` folder. You can then copy these into the destination project and everything should work as-is

Ah, thank you for the quick response. This got me further, I've got another problem now that I'll make another issue for.
