### ISSUE TITLE
Thread 'main' panicked at main.rs:162:72

### ISSUE THREAD

**Issue by TheUltimateNuke** [zCubed3/asset_migrator#4]
Now I get an error, after using the correct syntax.
I set up a PowerShell script to help me with multiple scene files:

```
foreach ($file in Get-ChildItem "D:\SteamLibrary\steamapps\common\<game>\<game>_Data\Ripped\<game>\ExportedProject\Assets" -Recurse -Include "*.unity") {
    echo $file
    Start-Process -Wait -FilePath 'D:\Dev Stuff\Programs\PrefabConverter\asset_migrator.exe' -ArgumentList "`"D:\SteamLibrary\steamapps\common\<game>\<game>_Data\Ripped\<game>\ExportedProject\Assets`" `"D:\Dev Stuff\Projects\VS Community\Unity\My project\Assets`" `"($file)`"" -NoNewWindow
}
```

All it does is run the program for every .unity file in the ripped project directory. I've tried running the program by itself, and i get the same error as when i run it using the script:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StripPrefixError(())', src\main.rs:162:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
All I can gather from this error method, having very little knowledge in Rust, is that it can't get the .unity file's path because it somehow ends up as type 'Err'.

**Comment by zCubed3** [comment]
Wow so you found an accidental oversight. If your paths are relative the asset directory it'll panic! I'm making a bugfix for it rn and I'll post a release soon

**Comment by zCubed3** [comment]
Alright this problem should be fixed in the latest release. Please let me know if it was actually fixed 👍
